# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

variables:
  mavenPomFile : 'pom.xml'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:

- stage:
  displayName: Build
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CacheBeta@0
      displayName: Cache Maven local repo
      inputs:
        key: 'maven | "$(Agent.OS)" | $(mavenPomFile)'
        restoreKeys: |
          maven | "$(Agent.OS)"
          maven
        path: $(MAVEN_CACHE_FOLDER)

    - task: Maven@3
      displayName: Build function
      inputs:
        mavenPomFile: $(mavenPomFile)
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'clean package'
        options: '--batch-mode -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -X'

    - task: PublishTestResults@2
      displayName: Publish test results
      inputs:
        testResultsFiles: '**/TEST-*.xml'

    - task: ArchiveFiles@2
      displayName: Create zipped package
      inputs:
        rootFolderOrFile: '$(Build.Repository.LocalPath)/target/azure-functions/fabrikam-functions-20231231163936350'
        includeRootFolder: false 
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(funcAppName)$(Build.BuildId).zip' 

    - publish: '$(Build.ArtifactStagingDirectory)/$(funcAppName)$(Build.BuildId).zip'
      artifact: FunctionApp
      displayName: Publish build artifacts

- stage:
  displayName: Deploy
  condition: succeeded()
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: FunctionApp
      displayName: Download function package

    - task: AzureFunctionApp@1
      displayName: Deploy function app
      inputs:
        azureSubscription: 'Azure subscription 1(9b1a2a01-3ffe-4a11-8496-45e657c12712)'
        appType: 'functionApp'
        appName: 'fabrikam-functions-20231231163936350'
        package: '$(Pipeline.Workspace)/FunctionApp/$(funcAppName)$(Build.BuildId).zip'
        deploymentMethod: 'auto'